apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tochka.fullname" . }}-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "{{ .Values.secrets.fernetKey }}"
  FERNET_KEY: "{{ .Values.secrets.fernetKey }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password }}"
