apiVersion: v1
kind: Secret
metadata:
  name: tochka-secrets
  namespace: tochka
type: Opaque
data:
  fernetKey: blJTby10b0gycW1ZR1QtSkJiQnk4WWFldmNNaThCT3h6UmlIS2dBVmx4VT0=
  postgresPassword: Z2VuaXVzcGFzc3dvcmQ=
  telegramBotToken: NjAzNTU2ODc1MTpBQUVxbEhqR3NIUGJZaDRJMm1ES1JQTFhUZjNYcllQTTJiNA==
  telegramChatId: MTA3NzE4NjI5MQ==